### ISSUE TITLE
Default JSON collection Path

### ISSUE THREAD

**Issue by siggipop** [GuidoPreite/DRB_XrmToolBox#1]
In the XRM Toolbox version of DRB, I can't figure out where the default path to JSON collection is located. 
It loads a collection every time I open the plugin (I want to know which path). But if i save collection, the default path is always download folder. 
Would be great to be able to select a default load / save path.

**Comment by GuidoPreite** [comment]
the JSON collection is stored inside localStorage (inside the browser, the XTB version uses a browser runtime to execute DRB), if the app is loading a collection every time you open mean that has been saved with "Save State" option (by right click on the collection name).

The JSON collection inside the localStorage is actually saved with a key structured as DRB_{environmenturl} so you can have a saved collection for each environment, so based on the environment you load it will show the right collection (if present).

When the collection is saved a path is not specified, it saves to the default path of the browser. If you are interested the code is this function https://github.com/GuidoPreite/DRB/blob/main/js/drb.collection.js#L139

This behavior (the load folder and the default save folder) is a standard of the browser (for security reasons they can't know that you have a D drive for example).

Can you explain why you need this behavior? it has to do with source control? Maybe I can think of an alternative way for what you need.

**Comment by GuidoPreite** [comment]
As this issue is opened from a week without a reply I will close it. If you have additional questions please open a new one.
Thanks
