### ISSUE TITLE
Could not load file or assembly 'Microsoft.Web.WebView2.WinForms'

### ISSUE THREAD

**Issue by OliverFlint** [GuidoPreite/DRB_XrmToolBox#2]
Hi Guido, Hope I'm putting this is the correct place. After a recent update of the XrmToolBox I'm now receiving the following error when opening DRB. The same issue is happening on several windows PC's (Win10 and Win 11)

![image](https://user-images.githubusercontent.com/8300688/192359896-28d5da4e-5c5f-4ee2-a1d0-c2ae8d0e6cb1.png)

---
- Deployment: Online
- DB Version: 9.2.22091.192
- Connection Controls Version: 1.2022.7.53
- XrmToolBox Version: 1.2022.9.57
- Tool Version: 1.0.0.38

**Comment by GuidoPreite** [comment]
thanks @OliverFlint for reporting it. I just updated to the same version XTB you have (1.2022.9.57) and I also get the same error. I will check with Tanguy Touzard regarding this.

**Comment by OliverFlint** [comment]
Looks like it the nuget reference got updated in toolbox at the same time as the dataverse sdk...
https://github.com/MscrmTools/XrmToolBox/commit/593f3ee31870d955373a0a52f2c78265a7ba0a7b#diff-c63696c810ede27954d774c8f6d873f5a4a857536f17fba2cbe4ce38e27491e0

**Comment by GuidoPreite** [comment]
correct, the version of WebView2 component has been updated in the latest version of XTB. I need to verify with Tanguy if is something I need to update inside DRB, also to avoid that in the future this kind of behavior happens again.

**Comment by GuidoPreite** [comment]
Hi @OliverFlint, I release a new version (1.0.0.39) that should fix the problem with the latest version of XrmToolBox. Please test and let me know.
Thanks

**Comment by OliverFlint** [comment]
Fixed! Thanks for the speedy turnaround!
