### ISSUE TITLE
REST builder connects to the wrong environment in XrmToolBox

### ISSUE THREAD

**Issue by Enielezi** [GuidoPreite/DRB_XrmToolBox#3]
Hi,

I am trying to use REST builder but it somehow doesn't link to the environment connected in XrmToolBox. Instead it connects to the default environment. Has anyone experienced this?
I tried restarting XrmToolBox, changing connection etc but can't seem to get it to connect to correct sandbox enviroment.

![2022-11-24 16_46_30-Window](https://user-images.githubusercontent.com/5193268/203835875-0edac212-674e-4cd8-8d91-01a8285fd131.png)

**Comment by GuidoPreite** [comment]
Can you tell me which type of connection you created for this instance?
Did you try with another type of connection? (MFA, Client ID/ Client Secret,...)
Thanks

**Comment by Enielezi** [comment]
I used Microsoft Login Control to create the connection. It is an aad user which has MFA enabled. 
I don't get this problem with other XrmToolBox tools.
Thanks
![2022-11-24 23_05_37-Window](https://user-images.githubusercontent.com/5193268/203872735-c352b4cf-3856-41f5-ac17-03ed160db7a4.png)

**Comment by GuidoPreite** [comment]
Hi @Enielezi, I tried to replicate your issue (I connected with a user accessing multiple environments using the Microsoft Login Control) and it always connected me to the right instance selected inside the Microsoft Login Control.
It's happening always? Did you try to connect using OAuth/MFA or another method instead of Microsoft Login Control?

**Comment by Enielezi** [comment]
I tried with clinetid and it works fine:)

![image](https://user-images.githubusercontent.com/5193268/205324841-b807756c-ed23-41e4-8b6d-da5ff23dad92.png)




Still doesn't work with 'Ms Login Control' and when I try to open the tool with this connection is shows this error:

![image](https://user-images.githubusercontent.com/5193268/205323958-4a84955f-e3e8-48d0-9502-153586c7e109.png)

The url (obsfucated) is the wrong one!

There is no other logs within xrmtoolbox folder that I can see!

**Comment by GuidoPreite** [comment]
At least works with Client ID / Secret type. As I wrote before inside my trial it works also with the Microsoft Login Control so I am not able to replicate the issue. Also the screenshot and the log you posted are not useful for debugging your issue.
My tool for XrmToolBox uses a different method (WebView2) compared to the other tools (WinForms) so this may be a reason.
I will now close this ticket, if another user reported the same problem I will check again.

**Comment by Enielezi** [comment]
Thanks Guido, good to know it uses different connection method! That should be the reason.

If I find some time I will also create a branch and take a look, to see if a meaningful error is thrown during connection.
